{
  "airlineName":  "Delta",
  "code": "A12342",
  "departureDate":  "2015/07/11",
  "destination":  "CLE",
  "emptySeats": "17",
  "origin": "MUA",
  "planeType":  "Boing 727",
  "price":  "308.0"
 }